name: collage_bus_nufa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  firebase_core: ^2.25.4
  get: ^4.6.6
  http: ^1.2.0
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  cloud_firestore: ^4.15.4
  firebase_analytics: ^10.8.5
  firebase_crashlytics: ^3.4.14
  cloud_functions: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/playstore.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700