// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3wjUum0aH51E6KozahvatjKQhQTAz--8',
    appId: '1:921801174899:web:678d02a76f960472f8df06',
    messagingSenderId: '921801174899',
    projectId: 'collage-c56db',
    authDomain: 'collage-c56db.firebaseapp.com',
    storageBucket: 'collage-c56db.appspot.com',
    measurementId: 'G-XWQSRB5L48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrr2Xn5B_i_xMzYNleeBx1LC1xXQwft18',
    appId: '1:921801174899:android:d431fd08b8eea242f8df06',
    messagingSenderId: '921801174899',
    projectId: 'collage-c56db',
    storageBucket: 'collage-c56db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKuZQ6um8mKhUnTHnGts_yhvHN4-NuyQ0',
    appId: '1:921801174899:ios:bcb45096005f2c39f8df06',
    messagingSenderId: '921801174899',
    projectId: 'collage-c56db',
    storageBucket: 'collage-c56db.appspot.com',
    iosClientId: '921801174899-soo1kttq67heqmd6c9vq06q9sfl20n71.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKuZQ6um8mKhUnTHnGts_yhvHN4-NuyQ0',
    appId: '1:921801174899:ios:d28509ba8997d4d0f8df06',
    messagingSenderId: '921801174899',
    projectId: 'collage-c56db',
    storageBucket: 'collage-c56db.appspot.com',
    iosClientId: '921801174899-jd6v60mkc8lhst4mgkesnqud6a18c3kh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
