import 'package:collage_bus_nufa/message.dart';
import 'package:flutter/material.dart';

class payment extends StatelessWidget {
  payment({super.key});

  final List<String> users = [
    'Michael Wilson',
    'Vivienne Daniel',
    'Alexander Johnson',
    'Emma Thompson',
    'Jonah Stephens',
    'Julia Salazar',
    'Rowan Briggs',
    'Christopher White',
    'Olivia Lopez',
    'Joshua Martin',
    'Sophia Lee',
    'Andrew Jackson',
    'Isabella Perez',
    'Daniel Harris',
    'Ava Smith',
    'Matthew Clark',
    'Mia Lewis',
    'Anthony Young',
    'Charlotte Walker',
    'Joseph Allen',
    'Amelia King',
    'Thomas Wright',
    'Harper Rodriguez',
    'Jackson Moore',
    'Evelyn Hall',
    'Sebastian Taylor',
    'Abigail Brown',
    'Caleb Adams',
    'Elizabeth Jones',
    'Ryan Miller',
    'Madison Carter',
    'Nathan Roberts',
    'Chloe Garcia',
    'Lucas Lee',
    'Scarlett Martin',
    'Christian Anderson',
    'Grace Martinez',
    'Owen Thomas',
    'Zoe Hernandez',
    'Ethan White',
    'Lily Scott',
    'Maxwell Turner',
    'Aria Young',
    'Isaac Lopez',
    'Ellie Harris',
    'Gabriel Clark',
    'Hannah Robinson',
    'Benjamin Walker',
    'Nora Campbell',
    'Samuel Perez',
    'Addison Evans',
    'Carter Phillips',
    'Luna Mitchell',
    'Owen Collins',
    'Avery Rivera',
    'Wyatt Edwards',
    'Ella Nguyen',
    'Henry Morris',
    'Sofia Cook',
    'Logan Ortiz',
    'Camila Bailey',
    'Jayden Adams',
    'Layla Cooper',
    'Gavin Reed',
    'Milay Stewart',
    'Aiden Bell',
    'Isabelle Murphy',
    'Cooper Sanders',
    'Alice Barnes',
    'Julian Ross',
    'Kylie Coleman',
    'Levi Jenkins',
    'Lucy Perry',
    'Leo Powell',
    'Annie Richardson',
    'Josiah Simmons',
    'Lillian James',
    'Lincoln Ward',
    'Brianna Brooks',
    'Adam Price',
    'Violet Myers',
    'Grayson Foster',
    'Aubrey Russell',
    'Ian Howard',
    'Kayla Torres',
    'Nolan Jensen',
    'Sadie Reyes',
    'Easton Wells',
    'Adalyn Wood',
    'Carter Palmer',
    'Gabriella Knight',
    'Jeremiah Shaw',
    'Brooklyn Mason',
    'Mateo Holmes',
    'Paisley Boyd',
    'Julian Warren',
    'Mackenzie Dixon',
    'Brayden Hunt',
    'Jade Mills',
    'Bryson Andrews',
    'Eva Nichols',
    'Axel Spencer',
    'Norah Charles',
    'Landon West',
    'Maya Stevens',
    'Griffin Dean',
    'Leah Wagner',
    'Chase Fisher',
    'Jocelyn Hart',
    'Gavin Daniels',
    'Kinsley Lawrence',
    'Theodore Wheeler',
    'Amaya Black',
    'Jason Alexander',
    'Natalie Stone',
    'Colton Soto',
    'Alexandra Mcdonald',
    'Sawyer Freeman',
    'Piper Snyder',
    'Bryce Bates',
    'Marley Atkins',
    'Nathaniel Olson',
    'Kennedy Paul',
    'Liam Davenport',
    'Skylar Cruz',
    'Jaxon Banks',
    'Vivian Marshall',
    'Dylan Barnes',
    'Elise Gordon',
    'Waylon Day',
    'Rosalie Reed',
    'Micah Santiago',
    'Jordyn Fletcher',
    'Beau Lynch',
    'Alana Chan',
    'Emmett Mann',
    'Eden Hayes',
    'Elliott Grant',
    'Juliette Weaver',
    'Jude Ellis',
    'Annabelle Gardner',
    'Finn Bishop',
    'Harley Dawson',
    'Arthur Gilbert',
    'Megan Stanley',
    'Asher Barrett',
    'Cora Holland',
    'Kai Love',
    'Alaina Hamilton',
    'Declan Graham',
    'June Mckenzie',
    'Oscar Lane',
    'Kendra Webb',
    'Zachary George',
    'Marley Cunningham',
    'Jonah Stephens',
    'Julia Salazar',
    'Rowan Briggs',
    'Vivienne Daniel',
  ];

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          title: const Text("Students"),
          automaticallyImplyLeading: false,
        ),
        body: ListView.builder(
          itemCount: users.length,
          itemBuilder: (context, index) {
            return Column(
              children: [
                ListTile(
                  title: Text(users[index]),
                  onTap: () {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (context) => message(name: users[index]),
                      ),
                    );
                  },
                ),
                const Divider(),
              ],
            );
          },
        ),
      ),
    );
  }
}
